In [15]:
import pandas as pd
from pathlib import Path
import os

In [16]:
df = pd.read_csv("../data/main/edc_all_artists.csv")
df.drop_duplicates(inplace=True)
df.head()

   year            artist
0  2024             1080p
1  2024  A Shade of Black
2  2024           Aaron K
3  2024             Abana
4  2024        D. Zeledon

In [17]:
df = df.drop(columns=["year"])

In [18]:
df.to_csv("../data/main/edc_artists_no_duplicates.csv", index=False)

In [ ]:
df.count()

artist    1476
dtype: int64

In [ ]:
df1 = pd.read_csv("../data/main/edc_artists_no_duplicates.csv")
df1.drop_duplicates(inplace=True)

In [21]:
df["artist"].nunique()
df

                artist
0                1080p
1     A Shade of Black
2              Aaron K
3                Abana
4           D. Zeledon
...                ...
1471               YDG
1472       Yellow Claw
1473  Yoji Biomehanika
1474             Yosuf
1475              Zevy

[1476 rows x 1 columns]